name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging server
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          ssh -i ~/ssh_key root@
          cd devops-test && git pull
          pnpm install
          pnpm run build
          pm2 restart frontend
          pm2 restart http-server
          pm2 restart ws-server

